### ISSUE TITLE
how can I put title with url

### ISSUE THREAD

**Issue by whoizit** [achembarpu/pockyt#17]
I try to do this:
```
echo 'Usanov_Nauka-o-bogatstve.517832 http://ix.io/2fWf' | pockyt put -f '{title} {link}' -i redirect

```
nothing properly works

**Comment by arvindch** [comment]
Hi,

Currently, pockyt only supports ingestion of links, and not any metadata. Also, as per the [API Docs](https://getpocket.com/developer/docs/v3/add):
"title | string | optional
This can be included for cases where an item does not have a title, which is typical for image or PDF URLs. If Pocket detects a title from the content of the page, this parameter will be ignored."

Cheers!
