### ISSUE TITLE
Feature request: since flag for get requests

### ISSUE THREAD

**Issue by inputsh** [achembarpu/pockyt#18]
I'd love to be able to filter the articles by the date they were manipulated within Pocket. Some usage examples:

* Get all the articles I've added since Monday.
* Get all the articles I've archived this (or last) month.
* Get all the articles I've favourited this year.

Something like:

`pockyt get --since 2020-01-01 -s archived`

Pocket API's [get feature](https://getpocket.com/developer/docs/v3/retrieve) does have a since parameter, so it should definitely be possible.

**Comment by achembarpu** [comment]
Hey Aleksandar,

Hope you are doing well amidst this pandemic, and enjoying using pockyt.
Just getting around to this now, and have added support for `--since` in 1.4.3.

Cheers!
