### ISSUE TITLE
is it possible to get the entire article (as rendered by Pocket), not just the 'excerpt' ?

### ISSUE THREAD

**Issue by m040601** [achembarpu/pockyt#6]
I know that for example,
to to get the latest 5 items' links & excerpts and save them to a file:
pockyt get -n 5 -f '{link} - {excerpt}' -o readlater.txt
works

Is is also possible to get the entire article, as it is displayed and rendered on the pocket website ?
I mean just the extracted text, stored on the Pocket.
I dont want to download from the original server and extract the text on my computer again.

**Comment by arvindch** [comment]
[Article Content API](https://getpocket.com/developer/docs/v3/article-view) - Unfortunately, pocket does not provide extracted article content to api users without partner privileges.

I'm open to other ideas though. Maybe use a custom extraction method, via [BeautifulSoup](http://www.crummy.com/software/BeautifulSoup/), or something?

**Comment by m040601** [comment]
Thanks for your attention to this detail !
I see what you mean with the api issue, it makes sense.

But I'm still confused how there seems to be other ways to get the 'whole article' text directly from Pocket.For example with calibre, http://calibre-ebook.com , and it's python 'news recipe' scripts called 'readitlater.recipe'  (1) 

I'm no python expert, I can barely code some shell scripts and grasp a little bit of python.
I was wondering then,
how is it that using that script and calibre's command line tool 'ebook-convert' , http://manual.calibre-ebook.com/cli/ebook-convert.html  I do get the entire text of my Pocket articles.

When i used this like for example,
ebook-convert   ./readitlater.recipe  outputfile.txt  --username my-pocket@username.com --password my-pocket-account-password 
or
ebook-convert   ./readitlater.recipe  output.OEB  --username my-pocket@username.com --password my-pocket-account-password 

I can get either a text file, or just a bunch of html files,
with all my articles exactly as they are rendered by Pocket 




(1) 
a. as it is distributed when you install calibre,
https://gist.github.com/m040601/a4258870759f9ad8a6ee
it works for me
b. another fork of the same script (that was not working for me)
tbunnyman/ReadItLater-Calibre-Plugin 
https://github.com/tbunnyman/ReadItLater-Calibre-Plugin
This is an updated & modified version of the official Calibre plugin for Pocket (Formerly ReadItLater)

**Comment by arvindch** [comment]
Interesting. I'll check this out and think of a possible lightweight implementation.

Do you have the time to work on this, by any chance?

**Comment by m040601** [comment]
Cool ! Thanks for your interest.

> Do you have the time to work on this, by any chance?
Time yes, unfortunately not the skills to do it.
The only thing I can contribute is with research and feedback, as I like to thoroughly investigate and
compare all the available (python and others) solutions and implementations for this problem.

**Comment by arvindch** [comment]
[Newspaper](https://newspaper.readthedocs.org/en/latest/) seems to provide Pocket-like functionality.

If this seems like a good enough alternative, I'm willing to integrate it. Thoughts?

**Comment by arvindch** [comment]
Actually, the PyPi distribution of `newspaper` is outdated, and depends on a lot of heavy libraries - [see requirements](https://github.com/codelucas/newspaper/blob/0.0.9/requirements.txt).

Instead, a better alternative seems to be [readability-lxml](https://github.com/buriy/python-readability). Significantly lighter and simpler to use.

**Comment by arvindch** [comment]
I'm hacking away on this right now. Let's see how it goes.

**Comment by arvindch** [comment]
Oops, almost forgot. The reason I'm not considering the scripts you linked to is:
* They scrape `getpocket.com` directly, which is forbidden by their ToS.
* Since it's a scrape, the moment Pocket changes their html, it will fail.

However, if this solution isn't good enough, I might reconsider.

**Comment by billlyzhaoyh** [comment]
Is there any hack to this? I am going back to a historic collection of articles and what I have found is that the articles have been taken down by the news sites... I would think even saving the HTML response of the article at that time and store it into the DB will help tremendously

**Comment by arvindch** [comment]
@billlyzhaoyh - Good use-case, I had a bit of time to hack on this today. Managed to get HTML archiving working in [1.4.0](https://github.com/arvindch/pockyt/releases/tag/1.4.0).

Let me know if it works for you.

**Comment by achembarpu** [comment]
Closing as stale.
